# Generated by Django 5.0.2 on 2024-03-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0002_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombresPila',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre/s de pila'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de teléfono'),
        ),
    ]
