# Generated by Django 5.0.2 on 2024-03-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0003_alter_perfilusuario_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('billetera_virtual', 'Billetera Virtual')], max_length=50, verbose_name='Tipo de institución')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('paginaWeb', models.URLField(blank=True, max_length=255, null=True, verbose_name='Página Web')),
                ('telefonoServicioAlCliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono servicio al cliente')),
                ('aceptaCredito', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Proveedor de Pagos',
                'verbose_name_plural': 'Proveedores de Pagos',
            },
        ),
    ]
