# Generated by Django 5.0.2 on 2024-03-26 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0004_formadepago_proveedorpagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorpagos',
            name='aceptaCredito',
            field=models.BooleanField(verbose_name='Acepta Crédito'),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservas', models.FloatField()),
                ('proveedorPagos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.proveedorpagos', verbose_name='Proveedor de pagos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.perfilusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
