# Generated by Django 5.0.2 on 2024-03-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0005_alter_proveedorpagos_aceptacredito_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='nombreAlias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alias de la cuenta'),
        ),
    ]
