# Generated by Django 5.0.2 on 2024-03-27 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0007_alter_cuenta_proveedorpagos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formadepago',
            options={'verbose_name': 'Forma de pago', 'verbose_name_plural': 'Formas de pago'},
        ),
        migrations.AddField(
            model_name='formadepago',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finanzas_app.cuenta', verbose_name='Cuenta asociada'),
        ),
        migrations.AddField(
            model_name='formadepago',
            name='nombreAlias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alias de la forma de pago'),
        ),
        migrations.AddField(
            model_name='formadepago',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.perfilusuario', verbose_name='Usuario'),
        ),
    ]
