# Generated by Django 5.0.2 on 2024-03-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0009_egreso_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egreso',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
