# Generated by Django 5.0.2 on 2024-03-29 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0010_rename_descripción_egreso_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egreso',
            options={'verbose_name': 'Egreso', 'verbose_name_plural': 'Egresos'},
        ),
        migrations.AlterField(
            model_name='egreso',
            name='formaDePago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.formadepago', verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='formadepago',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.cuenta', verbose_name='Cuenta asociada'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.cuenta', verbose_name='Cuenta asociada'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.perfilusuario')),
            ],
        ),
    ]
